# Generated by Django 5.1.1 on 2024-09-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_category_alter_blog_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('tech', 'Tech'), ('lifestyle', 'Lifestyle'), ('education', 'Education'), ('travel', 'Travel'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=255),
        ),
    ]
